server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://lvwyh.com:3306/trpg?useUnicode=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: trpg
    password: ma19991102

    # Druid 常用配置（可按需调整）
    initialSize: 2
    maxActive: 20
    minIdle: 2
    maxWait: 60000
    testOnBorrow: false
    testWhileIdle: true
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20

mybatis:
  mapper-locations: classpath:mybatis/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false
  params: count=countSql

springdoc:
  api-docs:
    enabled: true          # 默认就是 true
    path: /v3/api-docs     # OpenAPI JSON 地址
  swagger-ui:
    enabled: true          # 默认就是 true
    path: /swagger-ui.html # 访问入口（也可用 /swagger-ui/index.html）
    tags-sorter: alpha
    operations-sorter: method